name: Publish web folder to gh-pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish web folder
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web
          branch: gh-pages
          clean: true
